### ISSUE TITLE
Remove me as a backer!

### ISSUE THREAD

**Issue by julmot** [OpenCollective/opencollective-website#526]
You haven't removed me as a backer – not even after I complained. You've debited my bank account 5 months without my approval. Seriously? Are you that unprofessional?
[opencollective.pdf](https://github.com/OpenCollective/opencollective-website/files/559490/opencollective.pdf)

**Comment by julmot** [comment]
cc @xdamman

**Comment by xdamman** [comment]
Hi Julian. Thanks for reaching out and I'm sorry to hear that you are not happy with your experience on Open Collective.

I looked in my emails and I couldn't find any email from you (hence the reason why I never answered your emails). I have no idea why I never got those emails. It wasn't even in my spam. I can see why you would be very frustrated to not having received an answer.

That said, I'm happy to refund you your monthly donation to Yeoman of $1/month starting from the date of the email in that PDF (June). Just send me your paypal email and I'll refund you $5.

Since then, the Open Collective platform has evolved a lot. You can now go to https://opencollective.com/subscriptions to manage your subscriptions and cancel anytime. Give it a try. We also have many more [open source projects](https://opencollective.com/opensource).

Thank you for having giving us a chance.

**Comment by julmot** [comment]
You might offer a contact form to make sure you receive emails.
